//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent_Task
    {
        public string ParentTask { get; set; }
        public int ParentId { get; set; }
    }
}
