//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public long TaskId { get; set; }
        public long ParentId { get; set; }
        public string TaskName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<long> Priority { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<long> UserId { get; set; }
    }
}
